// src/components/FormattedAuthors.tsx
import { Fragment } from 'react'

interface FormattedAuthorsProps {
  authors: string
  highlightName?: string
}

function parseAuthors(authors: string): string[] {
  return authors
    .split(',')
    .map((author) => author.trim())
    .filter(Boolean)
    .reduce<string[]>((parsedAuthors, author) => {
      if (/^[A-Z]{1,4}$/.test(author) && parsedAuthors.length > 0) {
        parsedAuthors[parsedAuthors.length - 1] += ` ${author}`
        return parsedAuthors
      }

      parsedAuthors.push(author)
      return parsedAuthors
    }, [])
}

export function FormattedAuthors({
  authors,
  highlightName = 'Smith CA',
}: FormattedAuthorsProps) {
  const parsedAuthors = parseAuthors(authors)

  return (
    <>
      {parsedAuthors.map((author, index) => {
        const isHighlighted = author === highlightName
        const isLast = index === parsedAuthors.length - 1

        return (
          <Fragment key={`${author}-${index}`}>
            <span className="inline-block whitespace-nowrap">
              {isHighlighted ? (
                <strong className="font-semibold">{author}</strong>
              ) : (
                author
              )}
              {!isLast && ','}
            </span>
            {!isLast && ' '}
          </Fragment>
        )
      })}
    </>
  )
}

// app/components/FormattedAuthors.vue
<script setup lang="ts">
interface FormattedAuthorsProps {
  authors: string
  highlightName?: string
}
const props = withDefaults(defineProps<FormattedAuthorsProps>(), {
  highlightName: 'Smith CA',
})
const parsed = computed(() => parseAuthors(props.authors))
</script>

<template>
  <span>
    <span
      v-for="(author, index) in parsed"
      :key="`${author}-${index}`"
      class="inline-block whitespace-nowrap"
    >
      <strong v-if="author === props.highlightName" class="font-semibold">{{ author }}</strong>
      <template v-else>{{ author }}</template>
      <template v-if="index !== parsed.length - 1">,&nbsp;</template>
    </span>
  </span>
</template>
