// src/components/Section.tsx
import { type ReactNode } from 'react'

interface SectionProps {
  title?: string
  id?: string
  as?: 'section' | 'article' | 'div'
  children: ReactNode
  className?: string
}

/**
 * Structural component for consistent vertical padding and optional section headings.
 * Creates visual rhythm between major page blocks through whitespace.
 */
export function Section({
  title,
  id,
  as: Component = 'section',
  children,
  className = '',
}: SectionProps) {
  return (
    <Component id={id} className={`py-16 ${className}`.trim()}>
      {title && (
        <h2
          className="font-semibold mb-6 text-text-primary"
          style={{ fontSize: 'clamp(1.25rem, 3vw, 1.75rem)' }}
        >
          {title}
        </h2>
      )}
      {children}
    </Component>
  )
}

// app/components/Section.vue
<script setup lang="ts">
interface SectionProps {
  title?: string
  id?: string
  as?: 'section' | 'article' | 'div'
  class?: string
}
const props = withDefaults(defineProps<SectionProps>(), {
  as: 'section',
  class: '',
})
</script>

<template>
  <component :is="props.as" :id="props.id" :class="['py-16', props.class]">
    <h2
      v-if="props.title"
      class="font-semibold mb-6 text-text-primary"
      :style="{ fontSize: 'clamp(1.25rem, 3vw, 1.75rem)' }"
    >
      {{ props.title }}
    </h2>
    <slot />
  </component>
</template>
