// app/pages/publications.vue
<script setup lang="ts">
import type { TypeFilter, YearFilter } from '~/utils/filter-publications'

useSeoMeta({ title: 'Publications | Courtney A. Smith, MD, MS' })

const typeFilter = ref<TypeFilter>('all')
const yearFilter = ref<YearFilter>('all')
const firstAuthorOnly = ref(false)

const filtered = computed(() =>
  filterPublications(publications, typeFilter.value, yearFilter.value, firstAuthorOnly.value),
)
const totalCount = computed(() => publications.filter((p) => p.kind !== 'submitted').length)
</script>

<template>
  <Container size="content">
    <PageHeader title="Publications" intro="Peer-reviewed articles, abstracts, and presentations." />

    <div class="pb-6 space-y-4">
      <div class="flex flex-wrap gap-2">
        <FilterPill :active="typeFilter === 'all'" @click="typeFilter = 'all'">All</FilterPill>
        <FilterPill :active="typeFilter === 'article'" @click="typeFilter = 'article'">Manuscripts</FilterPill>
        <FilterPill :active="typeFilter === 'published-abstract'" @click="typeFilter = 'published-abstract'">Abstracts</FilterPill>
        <span class="w-px bg-border-subtle mx-1" />
        <FilterPill :active="yearFilter === 'all'" @click="yearFilter = 'all'">All Years</FilterPill>
        <FilterPill :active="yearFilter === '2026'" @click="yearFilter = '2026'">2026</FilterPill>
        <FilterPill :active="yearFilter === '2025'" @click="yearFilter = '2025'">2025</FilterPill>
        <FilterPill :active="yearFilter === '2024'" @click="yearFilter = '2024'">2024</FilterPill>
        <FilterPill :active="yearFilter === 'earlier'" @click="yearFilter = 'earlier'">Earlier</FilterPill>
      </div>

      <label class="inline-flex items-center gap-2 cursor-pointer">
        <input v-model="firstAuthorOnly" type="checkbox" class="w-4 h-4 rounded border-border accent-accent">
        <span class="text-sm text-text-secondary">First author only</span>
      </label>
    </div>

    <p class="text-sm text-text-muted mb-4">
      Showing {{ filtered.length }} of {{ totalCount }} publications
    </p>

    <div class="pb-16">
      <template v-if="filtered.length > 0">
        <PublicationListItem v-for="pub in filtered" :key="pub.id" :publication="pub" />
      </template>
      <p v-else class="py-8 text-center text-text-secondary">
        No publications match these filters. Try adjusting your selection.
      </p>
    </div>
  </Container>
</template>

// src/app/publications/page.tsx
'use client'

import { useState, useMemo } from 'react'
import { Container } from '@/components/Container'
import { PageHeader } from '@/components/PageHeader'
import { FormattedAuthors } from '@/components/FormattedAuthors'
import { publications } from '@/data/publications'
import type { Publication } from '@/types'

type TypeFilter = 'all' | 'article' | 'published-abstract'
type YearFilter = 'all' | '2026' | '2025' | '2024' | 'earlier'

function getPublicationUrl(pub: Publication): string | null {
  if (pub.url) return pub.url
  if (pub.pmid) return `https://pubmed.ncbi.nlm.nih.gov/${pub.pmid}/`
  if (pub.doi) return `https://doi.org/${pub.doi}`
  return null
}

function FilterPill({
  active,
  onClick,
  children,
}: {
  active: boolean
  onClick: () => void
  children: React.ReactNode
}) {
  return (
    <button
      onClick={onClick}
      className={`
        inline-flex items-center px-3 py-1.5 rounded-full text-sm
        transition-all duration-150 ease-out
        ${active
          ? 'bg-accent-subtle text-accent border border-accent'
          : 'bg-bg-secondary text-text-secondary border border-border-subtle hover:border-accent'
        }
      `}
    >
      {children}
    </button>
  )
}

function PublicationListItem({
  publication,
}: {
  publication: Publication
}) {
  const { title, authors, journal, year, tags } = publication
  const publicationUrl = getPublicationUrl(publication)

  return (
    <article
      className="py-4 border-b border-border-subtle last:border-b-0 transition-opacity duration-150"
    >
      <h3 className="font-medium text-text-primary leading-snug">
        {publicationUrl ? (
          <a
            href={publicationUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-accent transition-colors duration-150"
          >
            {title}
          </a>
        ) : (
          title
        )}
      </h3>
      <p className="mt-1 max-w-none text-sm text-text-secondary">
        <FormattedAuthors authors={authors} />
      </p>
      <p className="mt-0.5 text-sm text-text-muted">
        <em>{journal}</em>, {year}
      </p>
      {tags.length > 0 && (
        <div className="mt-2 flex flex-wrap gap-1">
          {tags.map((tag) => (
            <span
              key={tag}
              className="inline-flex px-2 py-0.5 text-xs rounded-full bg-accent-subtle text-accent"
            >
              {tag}
            </span>
          ))}
        </div>
      )}
    </article>
  )
}

export default function PublicationsPage() {
  const [typeFilter, setTypeFilter] = useState<TypeFilter>('all')
  const [yearFilter, setYearFilter] = useState<YearFilter>('all')
  const [firstAuthorOnly, setFirstAuthorOnly] = useState(false)

  const filteredPublications = useMemo(() => {
    return publications.filter((pub) => {
      // Exclude submitted/unpublished
      if (pub.kind === 'submitted') return false

      // Type filter
      if (typeFilter === 'article' && pub.kind !== 'article') return false
      if (typeFilter === 'published-abstract' && pub.kind !== 'published-abstract') return false

      // Year filter
      if (yearFilter === '2026' && pub.year !== 2026) return false
      if (yearFilter === '2025' && pub.year !== 2025) return false
      if (yearFilter === '2024' && pub.year !== 2024) return false
      if (yearFilter === 'earlier' && pub.year >= 2024) return false

      // First author filter
      if (firstAuthorOnly && !pub.isFirstAuthor) return false

      return true
    }).sort((a, b) => b.year - a.year)
  }, [typeFilter, yearFilter, firstAuthorOnly])

  const totalCount = publications.filter(p => p.kind !== 'submitted').length

  return (
    <>
      {/* Add metadata via document title since this is a client component */}
      <title>Publications | Courtney A. Smith, MD, MS</title>

      <Container size="content">
        <PageHeader
          title="Publications"
          intro="Peer-reviewed articles, abstracts, and presentations."
        />

        {/* Filter Bar */}
        <div className="pb-6 space-y-4">
          {/* Type filters */}
          <div className="flex flex-wrap gap-2">
            <FilterPill
              active={typeFilter === 'all'}
              onClick={() => setTypeFilter('all')}
            >
              All
            </FilterPill>
            <FilterPill
              active={typeFilter === 'article'}
              onClick={() => setTypeFilter('article')}
            >
              Manuscripts
            </FilterPill>
            <FilterPill
              active={typeFilter === 'published-abstract'}
              onClick={() => setTypeFilter('published-abstract')}
            >
              Abstracts
            </FilterPill>

            <span className="w-px bg-border-subtle mx-1" />

            {/* Year filters */}
            <FilterPill
              active={yearFilter === 'all'}
              onClick={() => setYearFilter('all')}
            >
              All Years
            </FilterPill>
            <FilterPill
              active={yearFilter === '2026'}
              onClick={() => setYearFilter('2026')}
            >
              2026
            </FilterPill>
            <FilterPill
              active={yearFilter === '2025'}
              onClick={() => setYearFilter('2025')}
            >
              2025
            </FilterPill>
            <FilterPill
              active={yearFilter === '2024'}
              onClick={() => setYearFilter('2024')}
            >
              2024
            </FilterPill>
            <FilterPill
              active={yearFilter === 'earlier'}
              onClick={() => setYearFilter('earlier')}
            >
              Earlier
            </FilterPill>
          </div>

          {/* First author toggle */}
          <label className="inline-flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={firstAuthorOnly}
              onChange={(e) => setFirstAuthorOnly(e.target.checked)}
              className="w-4 h-4 rounded border-border accent-accent"
            />
            <span className="text-sm text-text-secondary">
              First author only
            </span>
          </label>
        </div>

        {/* Results count */}
        <p className="text-sm text-text-muted mb-4">
          Showing {filteredPublications.length} of {totalCount} publications
        </p>

        {/* Publication list */}
        <div className="pb-16">
          {filteredPublications.length > 0 ? (
            filteredPublications.map((pub) => (
              <PublicationListItem key={pub.id} publication={pub} />
            ))
          ) : (
            <p className="py-8 text-center text-text-secondary">
              No publications match these filters. Try adjusting your selection.
            </p>
          )}
        </div>
      </Container>
    </>
  )
}
